### ISSUE TITLE
How do I fix the connnection error

### ISSUE THREAD

**Issue by scottming** [badetitou/vscode-pharo#2] opened 2021-02-24 06:48 UTC
I'm pretty sure I've installed lsp in my image

![image](https://user-images.githubusercontent.com/12830256/108959171-03339a80-76af-11eb-887e-b344ddbe6f3d.png)

This is my vscode settings:

![image](https://user-images.githubusercontent.com/12830256/108959224-134b7a00-76af-11eb-9b4e-c92ed3b6d820.png)

This is the vscode output when I open a `.st` file:

```
[Error - 2:42:55 PM] Connection to server is erroring. Shutting down server.
[Error - 2:42:55 PM] Connection to server is erroring. Shutting down server
```

My system is: `macOS bigsur version 11.2`

**Comment by badetitou** [comment] 2021-02-24 10:03
I would try to use Pharo 8 before :-).
I have packaged the code for Pharo 9 but not tested it.

Is it VSCode that starts the Pharo image, or did you open the image by hand?
It should be VSCode that starts the server.

(I should add a command that restarts the extension)

**Comment by scottming** [comment] 2021-02-24 10:54
VsCode doesn't start the image automatically, and then it's the same problem whether I use 8 or 9.

**Comment by badetitou** [comment] 2021-02-24 10:59
Ok, the problem is then in the image startup...
How do you start the image using the command line in macOS?
Is it with

```sh
/path/to/Pharo.app /path/to/LSP.image
```

Or do you have to point out an executable file inside `Pharo.app`?

**Comment by scottming** [comment] 2021-02-24 11:24
After I changed the vm path to this executable path
`/path/to/Pharo.app/Contents/MacOS/Pharo`
, the plugin works.

But I found a new bug, when I use format, the Chinese comment I write will be formatted into something I don't know.

**old: **

```
"
内部产品，即服务
"
Class {
	#name : #HcProduct,
	#superclass : #Object,
	#instVars : [
		'title',
		'services'
	],
	#category : #'HcSCRM-Core'
}
```

**new:**

```
 Class. "
���产�������
"
{ 
	 #name.
	 :.
	 #HcProduct , #superclass.
	 :.
	 #Object , #instVars.
	 :.
	 [ 'title' , 'services' ] , #category.
	 :.
	#'HcSCRM-Core' }
```

**Comment by badetitou** [comment] 2021-02-24 11:40
I know the formater for tonel file is broken. 
And I think I support utf-8 by default? But maybe not chinese character. Please consider opening two new issues for each problem. And I'll close this one

**Comment by badetitou** [comment] 2021-02-24 11:49
I added a hint in the ReadMe for the VM path in MacOS

**Comment by badetitou** [comment] 2021-02-24 12:14
I can reproduce the problem with the comment `内部产品，即服务`

**Closed as completed** 2021-02-24 12:38 UTC

**Comment by badetitou** [comment] 2021-02-24 12:41
@scottming, I have introduced a better formater for Tonel file.
I will have a look for the Chinese character
