### ISSUE TITLE
Cannot start the plugin in ArchLinux w/ P9.0

### ISSUE THREAD

**Issue by gavr123456789** [badetitou/vscode-pharo#19] opened 2021-06-15 11:03 UTC
my procedure:  
1) Installed plugin in to VSC
2) Downloaded Pharo64-9.0-PLS.zip from https://github.com/badetitou/Pharo-LanguageServer/releases 
3) Downloaded headless 9.0 VM from https://files.pharo.org/vm/pharo-spur64-headless/Linux-x86_64/  
4) set path to image and path to VM in extension settings  
![image](https://user-images.githubusercontent.com/30507409/122041797-024f8180-cde2-11eb-9fdf-ee8a8b29c9bf.png)  
![image](https://user-images.githubusercontent.com/30507409/122041825-0a0f2600-cde2-11eb-8790-a5322ca25ff5.png)   
![image](https://user-images.githubusercontent.com/30507409/122041858-185d4200-cde2-11eb-9a0a-a9b11e92d6bb.png)  

But nothing happening when I open .st files (only notification client started)  

https://user-images.githubusercontent.com/30507409/122042209-86096e00-cde2-11eb-891b-753278e64784.mp4

Arch linux

**Comment by badetitou** [comment] 2021-06-15 11:18
Hello,

It looks like the plugin finds the VM and the Image, but there is a problem at the startup of everything.
Can you try with this VM (https://files.pharo.org/get-files/90/pharo64-linux-headless-latest.zip)
I know that sometimes an incorrect VM might break everything when using headless mode.

I'll test with my Archlinux as soon as possible

**Comment by badetitou** [comment] 2021-06-15 11:19
If it does not work, please consider using a not headless VM and report a screenshot of the debugger that will appear in the image.

**Comment by gavr123456789** [comment] 2021-06-15 11:51
I also noticed that it doesn't matter how valid the Path To Image string is.  
The Client Started message still occurs.  

https://user-images.githubusercontent.com/30507409/122047779-32e6e980-cde9-11eb-850a-8365c33e2ded.mp4
  
So I think the problem is in the Image

**Comment by gavr123456789** [comment] 2021-06-15 11:58
>  Can you try with this VM (https://files.pharo.org/get-files/90/pharo64-linux-headless-latest.zip)
  
All same.  

Tried with usual headVM from https://files.pharo.org/vm/pharo-spur64/Linux-x86_64/PharoVM-9.0.0-f519c4c-Linux-x86_64-stockReplacement-bin.zip  
No errors there  
![image](https://user-images.githubusercontent.com/30507409/122048574-1f884e00-cdea-11eb-85e4-c50f35a66138.png)

**Comment by gavr123456789** [comment] 2021-06-15 12:27
And this is happening when I try with Pharo 8 vm from pharoLauncher and Pharo64-8.0-PLS.image   
![image](https://user-images.githubusercontent.com/30507409/122052256-2a44e200-cdee-11eb-96e6-bd259fc04617.png)

**Comment by badetitou** [comment] 2021-06-15 12:39
May I ask how did you download the pharo launcher?
Using https://aur.archlinux.org/packages/pharo-launcher/ ?

Because this error with git and "External module not found" is often a problem of right access (note that it is not linked to the issue with VSCode)

**Comment by gavr123456789** [comment] 2021-06-15 12:53
No, from official site https://pharo.org/download  
But with 90 there are no errors, so I think that with 80 it is not so important

**Comment by badetitou** [comment] 2021-06-15 13:15
Ok, so there are three issues: 

1. there is no error when the path is wrong (_i.e._ the process does not start)
2. there is no error when the process dies (_i.e._ the process is killed)
3. We cannot use Pharo 9.0 in headless in ArchLinux

**Comment by gavr123456789** [comment] 2021-06-15 13:37
> We cannot use Pharo 9.0 in headless in ArchLinux  
  
And not headless too(

**Comment by gavr123456789** [comment] 2021-06-15 13:39
Also, strange, but looks like it works with 9.0 for me in the past https://twitter.com/gavr123456789/status/1347282284173553666  
(Im from different machine now, but it was arch too, hmmmm)

**Comment by badetitou** [comment] 2021-06-15 13:39
I just tried w/ my Windows and I had no problem... I'll check later with the arch Linux one.. this is super strange

**Comment by gavr123456789** [comment] 2021-06-15 15:12
With 1.1.1 version I see this after start  
![image](https://user-images.githubusercontent.com/30507409/122078445-456f1c00-ce05-11eb-90ad-f313354603ac.png)
  
On 1.1.2 nothing   
![image](https://user-images.githubusercontent.com/30507409/122078813-87985d80-ce05-11eb-9ac1-27751b59314e.png)

**Comment by badetitou** [comment] 2021-06-15 17:24
And version 1.1.3 does not work?

**Comment by gavr123456789** [comment] 2021-06-15 22:09
yes it was with the latest version from the start. I just tried old because of this tweet. I also came home and here the same problem

**Comment by gavr123456789** [comment] 2021-06-16 08:39
![image](https://user-images.githubusercontent.com/30507409/122187141-6f711e80-ce97-11eb-8e5f-712121819c45.png)

ALso, I'm not sure if this could be related to the problem but trying to download packages via Metacello results in an error with libgit2

**Comment by badetitou** [comment] 2021-06-17 06:09
This is super strange the error with libgit...
Maybe you can ask in the [pharo repository](https://github.com/pharo-project/pharo/issues).

**Comment by badetitou** [comment] 2021-06-17 06:12
I have released a new version of the VSCode plugin that should show a popup when the image crash. Can you update the extension and test if the popup appears (in VSCode)

v1.0.6
Add error message when the process dies
Check that the path to the VM and to the image exist

**Comment by badetitou** [comment] 2021-06-20 12:57
Ok, I can reproduce the bug with my archlinux

**Comment by gavr123456789** [comment] 2021-06-20 13:08
> Can you update the extension and test if the popup appears  
  
Nice, will try tomorrow

**Comment by badetitou** [comment] 2021-06-20 13:40
It looks like the buffer of Window for `stdio` does not work the same way as the one of archlinux.
And it can create problem since we use stdio to transmit the port used by the Pharo Language Server.
I now use `flush` in Pharo Language Server, and I have released a new version with the bug fix.
Please confirm everything is ok now with version v1.1.4 : https://github.com/badetitou/Pharo-LanguageServer/releases/tag/v1.1.4

**Comment by gavr123456789** [comment] 2021-06-20 14:31
On start it seams to work, but then there are non stop this error spam  
![image](https://user-images.githubusercontent.com/30507409/122677961-5517a780-d1ed-11eb-9979-93f2e9f409a5.png)

**Comment by gavr123456789** [comment] 2021-06-20 14:32
![image](https://user-images.githubusercontent.com/30507409/122677986-7aa4b100-d1ed-11eb-881e-0bf49ebdf76c.png)

**Comment by badetitou** [comment] 2021-06-21 08:47
Nice, you are a good bug tracker :-) 

I have no idea of what this error can be... I'll look at it as soon as possible

**Comment by badetitou** [comment] 2021-08-18 06:29
Hi @gavr123456789 

Your problem with ArchLinux and P9 was reported in the AUR repo of pharo-launcher (that I maintain too...)
https://aur.archlinux.org/packages/pharo-launcher/

And then reported in the pharo project
https://github.com/pharo-project/pharo/issues/9729

I'm trying to find a good solution for Arch users. But I did not find one yet.

**Comment by badetitou** [comment] 2021-08-19 17:22
The bug with isScripting should be fixed
Also, the bug with archlinux and Pharo 9 is fixed in the last Pharo launcher

**Closed as completed** 2021-08-19 17:23 UTC
Labels: bug
